name: publish-api-documentation

on:
  workflow_dispatch:
  push:
    tags:
      - v3.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: "gh-pages"
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Merge changes from 3.0 branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge origin/3.0 -X theirs
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install GNS3 server
      run: |
        python setup.py install
    - name: Generate the API documentation
      run: |
        cd scripts
        python3 publish_api_documentation.py
    - name: Publish the API documentation
      run: |
        git add docs
        git status
        git commit -m "Publish API documentation"
        git push
